# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_auto_20170309_0015'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='credit_account',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='debit_account',
        ),
        migrations.AddField(
            model_name='journal',
            name='date',
            field=models.DateField(default='1994-10-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='for_account',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='journalforaccount', to='ledgers.Ledgers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='to_Account',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='journaltoaccount', to='ledgers.Ledgers'),
            preserve_default=False,
        ),
    ]
