# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_auto_20170309_0015'),
        ('journal', '0002_auto_20170414_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='to_Account',
        ),
        migrations.AddField(
            model_name='journal',
            name='to_Account',
            field=models.ManyToManyField(related_name='journaltoaccount', to='ledgers.Ledgers'),
        ),
    ]
