# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20170413_2305'),
        ('journal', '0003_auto_20170414_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='company',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
