# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20170414_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='journal',
            name='narration',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
