# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_journal_addaed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='addaed_by',
            new_name='added_by',
        ),
    ]
