# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0005_auto_20170228_2136'),
        ('ledgers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('narration', models.TextField(blank=True, max_length=100000)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('firstAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiptFirstAccount', to='ledgers.Ledgers')),
                ('secondAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiptSecondAccount', to='ledgers.Ledgers')),
            ],
        ),
    ]
