# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
