# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20170227_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
