# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_superuser',
            field=models.BooleanField(),
        ),
    ]
