# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_auto_20170227_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
