# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 17:05
from __future__ import unicode_literals

import Customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=Customer.models.user_directory_path),
        ),
    ]
