# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 07:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('rate', models.IntegerField()),
                ('discount', models.IntegerField(blank=True)),
                ('batch_no', models.IntegerField(blank=True)),
                ('manufacturing_date', models.DateField(blank=True)),
                ('expiry_date', models.DateField(blank=True)),
                ('tax', models.IntegerField()),
                ('location', models.CharField(max_length=1000)),
                ('manufacturing_company', models.CharField(max_length=1000)),
                ('mrp', models.IntegerField(blank=True)),
                ('purchase_price', models.IntegerField(null=True)),
                ('hsn_code', models.IntegerField(blank=True)),
                ('sac_code', models.IntegerField(blank=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
