# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170528_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(),
        ),
    ]
