# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgers', '0006_auto_20170526_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('closing_balance', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalsname', to='ledgers.Ledgers')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalstoaccount', to='ledgers.Ledgers')),
            ],
        ),
    ]
