# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_auto_20170309_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgers',
            name='credit_account',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ledgers',
            name='debit_account',
            field=models.IntegerField(default=0),
        ),
    ]
