# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0003_auto_20170414_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgers',
            old_name='credit_account',
            new_name='credit_amount',
        ),
        migrations.RenameField(
            model_name='ledgers',
            old_name='debit_account',
            new_name='debit_amount',
        ),
    ]
