# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0004_auto_20170414_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgers',
            name='primary',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
