# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledgers', '0005_ledgers_primary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgers',
            old_name='primary',
            new_name='primary_group',
        ),
        migrations.RenameField(
            model_name='ledgers',
            old_name='groups',
            new_name='secondry_group',
        ),
        migrations.RemoveField(
            model_name='ledgers',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='ledgers',
            name='type',
        ),
        migrations.AddField(
            model_name='ledgers',
            name='added_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgers',
            name='tertiary_group',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
