# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgers', '0002_auto_20170309_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trialbalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(max_length=1000)),
                ('debitAmount', models.IntegerField()),
                ('creditAmount', models.IntegerField()),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledgers.Ledgers')),
            ],
        ),
    ]
