# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20170302_0706'),
        ('trialbalance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
            preserve_default=False,
        ),
    ]
