# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('pin_code', models.IntegerField(max_length=1000)),
                ('zip_code', models.IntegerField(max_length=1000)),
                ('telephone_number', models.IntegerField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('currency_symbols', models.CharField(max_length=1000)),
                ('maintain_only', models.CharField(max_length=1000)),
                ('Accounts', models.CharField(max_length=1000)),
                ('accounts_with_inventory', models.CharField(max_length=1000)),
                ('financial_year_from', models.DateField(max_length=1000)),
                ('books_begining_from', models.DateField(max_length=1000)),
                ('show_amounts_in_millions', models.BooleanField(max_length=100)),
            ],
        ),
    ]
