# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comany',
            old_name='books_begining_from',
            new_name='books_beginning_from',
        ),
    ]
