# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20170228_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contra',
            name='addedBy',
        ),
        migrations.RemoveField(
            model_name='contra',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contra',
            name='firstAccount',
        ),
        migrations.RemoveField(
            model_name='contra',
            name='secondAccount',
        ),
        migrations.RemoveField(
            model_name='ledgers',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='addedBy',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='firstAccount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='secondAccount',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='addedBy',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='company',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='firstAccount',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='secondAccount',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='Contra',
        ),
        migrations.DeleteModel(
            name='Ledgers',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
