# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20170302_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='accounts_with_inventory',
            field=models.BooleanField(),
        ),
    ]
