# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0007_auto_20170302_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='admin',
        ),
        migrations.AddField(
            model_name='company',
            name='admin',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
