# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-13 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20170408_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cin_number',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='gst_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
