# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20170413_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cin_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='gst_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
