# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0003_auto_20170414_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice', models.IntegerField()),
                ('party_name', models.CharField(max_length=1000)),
                ('reference', models.IntegerField()),
                ('payment_method', models.CharField(max_length=1000)),
                ('journals', models.ManyToManyField(related_name='juurnal', to='journal.Journal')),
            ],
        ),
    ]
