# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 07:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_auto_20170418_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='added_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
