# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sales_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='total_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
