# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20170514_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='reference',
        ),
    ]
